fix: may overwrite .js, cjs and other build output
shigma/atsc pull request #2
Opened 2024-05-30 14:39 UTC by ktKongTong

may fix: https://github.com/shigma/atsc/issues/1

2024-06-04 20:02 UTC, shigma requested changes

2024-06-04 20:02 UTC, shigma commented on src/index.ts
> +  ignore?: string[]
```suggestion
  ignored?: string[]
```

2024-06-04 20:02 UTC, shigma commented on src/index.ts
> +    if(converters.includes(ext) && ['.yml', '.yaml'].includes()) {
```suggestion
    if (converters.includes(ext) && ['.yml', '.yaml'].includes()) {
```

下面 else 也改。

2024-06-05 04:25 UTC, ktKongTong commented on src/index.ts
> +    }else {
```suggestion
    } else {
```

2024-06-05 04:26 UTC, ktKongTong commented on src/index.ts
> +  const ignore = config.atsc?.ignore || ['.ts', '.mts', '.cts', '.tsx', '.mjs', '.cjs', '.js', '.jsx']
```suggestion
  const ignored = config.atsc?.ignored || ['.ts', '.mts', '.cts', '.tsx', '.mjs', '.cjs', '.js', '.jsx']
```

2024-06-05 04:26 UTC, ktKongTong commented on src/index.ts
> +    if (ignore.includes(ext)) return
```suggestion
    if (ignored.includes(ext)) return
```

2024-06-06 18:42 UTC, shigma reviewed
写完最好自己检查一下（）

2024-06-06 18:42 UTC, shigma commented on src/index.ts
> +    if (converters.includes(ext) && ['.yml', '.yaml'].includes()) {
```suggestion
    if (converters.includes(ext)) {
```

2024-06-06 18:50 UTC, ktKongTong commented on src/index.ts
> +    if (converters.includes(ext) && ['.yml', '.yaml'].includes()) {
该 `if` 段中包含的代码仅适用于 `yaml` 文件，我不认为这是可以删除的

2024-06-06 18:52 UTC, ktKongTong commented on src/index.ts
> +    if (converters.includes(ext) && ['.yml', '.yaml'].includes()) {
```suggestion
    if (converters.includes(ext) && ['.yml', '.yaml'].includes(ext)) {
```

2024-06-06 18:55 UTC, ktKongTong commented on src/index.ts
> +    if (converters.includes(ext)) {
```suggestion
    if (converters.includes(ext) && ['.yml', '.yaml'].includes(ext)) {
```

2024-06-06 19:02 UTC, shigma commented on src/index.ts
> +    if (converters.includes(ext) && ['.yml', '.yaml'].includes()) {
OK

2024-06-07 16:02 UTC, shigma approved these changes

2024-06-07 16:02 UTC, merged